version: "3"
services:
  abundantia_app:
    container_name: abundantia-dev-app
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=abundantia
    volumes:
      - data-volume:/var/lib/mysql
    command:
      mysqld --sql_mode=""
  abundantia_mysql:
    container_name: abundantia-dev-mysql
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "dockerize -wait tcp://subscription_core_redis:6379 -wait tcp://subscription-core-minio:9000 -wait tcp://abundantia_app:3306 && python manage.py runserver_plus 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ../:/code/
    ports:
      - "8000:8000"
      - "5555:5555"
    links:
      - abundantia_app
    depends_on:
      - abundantia_app
volumes:
  data-volume:
  s3-folder:
