version: "3"
services:
  abundantia_app:
    container_name: abundantia-dev-app
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    command: /bin/bash -c "dockerize -wait tcp://abundantia_redis:6379 -wait tcp://abundantia_mongo_db:27017 && python manage.py runserver_plus 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ../../:/code/
    ports:
      - "8000:8000"
      - "5555:5555"
    links:
      - abundantia_redis
      - abundantia_mongo_db
    depends_on:
      - abundantia_redis
      - abundantia_mongo_db
  abundantia_redis:
    container_name: abundantia-dev-redis
    image: redis:4.0.1-alpine
    ports:
      - "6379:6379"
  abundantia_mongo_db:
    image: mongo:4.0.6
    container_name: abundantia_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: another
      MONGO_INITDB_ROOT_PASSWORD: abundantia
      MONGO_INITDB_DATABASE: abundantia_db
    ports:
      - 27017:27017
